import { NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { promises as fs } from 'fs';
import path from 'path';
import { addMedia,getEvent,listMedia,updateMedia } from '@/lib/store';
import { uploadToDrive } from '@/lib/drive';
export const runtime='nodejs';
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;return NextResponse.json(await listMedia(id));}
export async function POST(req:Request,{params}:{params:Promise<{id:string}>}){try{const {id:eventId}=await params;const form=await req.formData();const file=form.get('file');if(!(file instanceof File))return NextResponse.json({error:'Archivo requerido'},{status:400});const event=await getEvent(eventId);if(!event)return NextResponse.json({error:'Evento no encontrado'},{status:404});const type=file.type||'video/webm';const inferred=type.includes('mp4')?'mp4':type.startsWith('image')?'jpg':'webm';const ext=file.name.split('.').pop()||inferred;const id=randomUUID();const stamp=new Date().toISOString().replace(/[-:]/g,'').replace('T','_').slice(0,15);const safeEvent=event.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/(^-|-$)/g,'').toLowerCase()||'evento';const filename=`${safeEvent}_${stamp}.${ext}`;const storedName=`${id}.${ext}`;const dir=path.join(process.env.MEDIA_DIR||path.join(process.cwd(),'public/media'),eventId);await fs.mkdir(dir,{recursive:true});const buffer=Buffer.from(await file.arrayBuffer());if(!buffer.length)return NextResponse.json({error:'La grabación llegó vacía al servidor'},{status:400});await fs.writeFile(path.join(dir,storedName),buffer);const item=await addMedia({id,eventId,kind:type.startsWith('video')?'video':'photo',url:`/api/media/${id}/file`,filename,storedName,mimeType:type,createdAt:new Date().toISOString(),guest:String(form.get('guest')||'')});if(event.driveFolderId){void uploadToDrive(event.driveFolderId,filename,type,buffer).then(driveFileId=>driveFileId?updateMedia(id,{driveFileId}):undefined).catch(error=>console.error('drive-backup',error))}return NextResponse.json({...item,driveStatus:event.driveFolderId?'queued':'disabled'},{status:201});}catch(error){console.error('media-upload',error);return NextResponse.json({error:error instanceof Error?error.message:'No se pudo procesar el archivo'},{status:500});}}
