'use client';
import { useEffect,useRef,useState } from 'react';
import QRCode from 'qrcode';
import type { BoothEvent,MediaItem } from '@/lib/types';

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const loadImage=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.crossOrigin='anonymous';img.onload=()=>resolve(img);img.onerror=reject;img.src=src});

export default function Booth({event}:{event:BoothEvent}){
  const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),stopRecording=useRef<(()=>void)|null>(null);
  const [mode,setMode]=useState<'photo'|'video'>('video'),[count,setCount]=useState<number|null>(null),[busy,setBusy]=useState(false),[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[duration,setDuration]=useState(event.duration),[result,setResult]=useState<MediaItem|null>(null),[qr,setQr]=useState(''),[error,setError]=useState(''),[appUrl,setAppUrl]=useState('');
  useEffect(()=>{navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:true}).then(s=>{stream.current=s;if(video.current)video.current.srcObject=s}).catch(()=>setError('Activa el permiso de cámara y micrófono para comenzar.'));return()=>stream.current?.getTracks().forEach(t=>t.stop())},[]);
  useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(c=>setAppUrl(c.appUrl)).catch(()=>setAppUrl(location.origin))},[]);
  useEffect(()=>{if(!recording)return;const started=Date.now();const timer=setInterval(()=>setElapsed(Math.min(duration,Math.floor((Date.now()-started)/1000))),250);return()=>clearInterval(timer)},[recording,duration]);
  async function countdown(){for(let i=3;i>0;i--){setCount(i);await sleep(800)}setCount(0);await sleep(350);setCount(null)}
  async function photoBlob(){const v=video.current!;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;const ctx=c.getContext('2d')!;ctx.drawImage(v,0,0,c.width,c.height);if(event.theme.frameUrl){try{ctx.drawImage(await loadImage(event.theme.frameUrl),0,0,c.width,c.height)}catch{setError('La foto se guardó, pero el marco externo no permitió ser incrustado. Usa un archivo local o una URL con CORS.')}}if(event.theme.logoUrl){try{const logo=await loadImage(event.theme.logoUrl);const w=c.width*.2,h=w*(logo.height/logo.width),m=c.width*.035;const corner=event.theme.logoCorner||'top-right';const x=corner.endsWith('right')?c.width-w-m:m;const y=corner.startsWith('bottom')?c.height-h-m:m;ctx.drawImage(logo,x,y,w,h)}catch{setError('La foto se guardó sin el logo externo. Usa un archivo local o una URL con CORS.')}}return new Promise<Blob>((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('No se pudo generar la foto')),'image/jpeg',.94))}
  async function videoBlob(){return new Promise<Blob>((resolve,reject)=>{const chunks:Blob[]=[];const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const rec=new MediaRecorder(stream.current!,{mimeType:mime});recorder.current=rec;let done=false;const finish=()=>{if(done)return;done=true;if(rec.state!=='inactive')rec.stop()};stopRecording.current=finish;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onerror=()=>reject(new Error('La grabación falló'));rec.onstop=()=>{setRecording(false);recorder.current=null;stopRecording.current=null;resolve(new Blob(chunks,{type:'video/webm'}))};rec.start(250);setElapsed(0);setRecording(true);window.setTimeout(finish,duration*1000)})}
  async function capture(){if(!stream.current||!video.current||busy)return;setBusy(true);setError('');setResult(null);try{await countdown();const blob=mode==='photo'?await photoBlob():await videoBlob();const f=new FormData();f.set('file',blob,mode==='photo'?'captura.jpg':'captura.webm');const response=await fetch(`/api/events/${event.id}/media`,{method:'POST',body:f});if(!response.ok)throw new Error((await response.json()).error||'No se pudo guardar');const saved=await response.json();setResult(saved);const share=`${appUrl||location.origin}/gallery/${event.id}?media=${saved.id}`;setQr(await QRCode.toDataURL(share,{margin:1,width:320,color:{dark:event.theme.background,light:'#ffffff'}}))}catch(e){setError(e instanceof Error?e.message:'No se pudo completar la captura')}finally{setBusy(false);setRecording(false)}}
  async function saveDuration(){const value=Math.max(3,Math.min(120,duration));setDuration(value);await fetch(`/api/events/${event.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({duration:value})})}
  const corner=event.theme.logoCorner||'top-right';
  return <main className="booth" style={{'--primary':event.theme.primary,'--accent':event.theme.accent,'--back':event.theme.background} as React.CSSProperties}><video ref={video} autoPlay playsInline muted/><div className="shade"/>{event.theme.frameUrl&&<img className="frame" src={event.theme.frameUrl} alt="Marco del evento"/>}{event.theme.logoUrl&&<img className={`boothLogo ${corner}`} src={event.theme.logoUrl} alt="Logo del evento"/>}<header><a href="/">◎ ORBIT 360</a><nav><a href={`/gallery/${event.id}`}>Galería</a><a href={`/project/${event.id}`} target="_blank">Proyectar</a></nav><span>{event.name}</span></header>{error&&<div className="notice">{error}</div>}{count!==null&&<div className="count">{count||'¡YA!'}</div>}{!busy&&!result&&<div className="captureUi"><span className="eyebrow">{event.client}</span><h1>{event.welcome}</h1><div className="mode"><button className={mode==='video'?'active':''} onClick={()=>setMode('video')}>Video 360</button><button className={mode==='photo'?'active':''} onClick={()=>setMode('photo')}>Foto</button></div>{mode==='video'&&<div className="durationControl"><label>Duración <input type="number" min="3" max="120" value={duration} onChange={e=>setDuration(Number(e.target.value))} onBlur={saveDuration}/> segundos</label></div>}<button className="shutter" onClick={capture} aria-label="Capturar"><i/></button><small>{mode==='video'?`${duration} segundos · ${event.format}`:'Foto de alta calidad'}</small></div>}{recording&&<div className="captureUi recordingUi"><div className="recording">● GRABANDO {elapsed}s / {duration}s</div><h1>Muévete. Gira. Brilla.</h1><button className="stopButton" onClick={()=>stopRecording.current?.()}>■ Terminar grabación</button></div>}{result&&<div className="result"><div>{result.kind==='video'?<video src={result.url} autoPlay loop controls/>:<img src={result.url} alt="Captura"/>}</div><section><span className="eyebrow">LISTO PARA COMPARTIR</span><h2>¡Tu momento quedó increíble!</h2><img className="qr" src={qr} alt="Código QR"/><p>Escanea para abrir esta captura, verla y descargarla.</p><div className="actions"><button onClick={()=>{setResult(null);setQr('')}}>Otra toma</button><a href={`${result.url}?download=1`}>Descargar</a><a href={`/gallery/${event.id}?media=${result.id}`}>Ver galería</a></div></section></div>}</main>
}
