'use client';
import { useEffect,useMemo,useState } from 'react';
import QRCode from 'qrcode';
import type { BoothEvent,MediaItem } from '@/lib/types';

const fileUrl=(item:MediaItem)=>`/api/media/${item.id}/file`;
const PAGE_SIZE=12;

export default function Gallery({event,project=false}:{event:BoothEvent;project?:boolean}){
  const [items,setItems]=useState<MediaItem[]>([]),[active,setActive]=useState(0),[selected,setSelected]=useState<MediaItem|null>(null),[qr,setQr]=useState(''),[view,setView]=useState<'preview'|'list'|'detail'>('preview'),[page,setPage]=useState(1),[copied,setCopied]=useState(false),[appUrl,setAppUrl]=useState('');
  useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(c=>setAppUrl(c.appUrl)).catch(()=>setAppUrl(location.origin))},[]);
  useEffect(()=>{const load=()=>fetch(`/api/events/${event.id}/media`,{cache:'no-store'}).then(r=>r.json()).then((data:MediaItem[])=>{setItems(data);const requested=new URLSearchParams(location.search).get('media');if(requested)setSelected(data.find(x=>x.id===requested)||null)});load();const t=setInterval(load,project?2500:10000);return()=>clearInterval(t)},[event.id,project]);
  useEffect(()=>{if(!project||items.length<2)return;const t=setInterval(()=>setActive(v=>(v+1)%items.length),6500);return()=>clearInterval(t)},[project,items.length]);
  useEffect(()=>{if(!selected){setQr('');return}QRCode.toDataURL(`${appUrl||location.origin}/gallery/${event.id}?media=${selected.id}`,{margin:1,width:300}).then(setQr)},[selected,event.id,appUrl]);
  const pages=Math.max(1,Math.ceil(items.length/PAGE_SIZE));const shown=useMemo(()=>items.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),[items,page]);
  async function copy(item:MediaItem){await navigator.clipboard.writeText(`${appUrl||location.origin}${fileUrl(item)}?download=1`);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  if(project){const item=items[active];return <main className="projection" style={{background:event.theme.background}}>{item?(item.kind==='video'?<video key={item.id} src={fileUrl(item)} autoPlay muted loop playsInline/>:<img key={item.id} src={fileUrl(item)} alt="Recuerdo proyectado"/>):<div><span>◎</span><h1>{event.name}</h1><p>Las nuevas capturas aparecerán aquí automáticamente.</p></div>}<header className="projectNav"><a href={`/booth/${event.id}`}>← Cabina</a><a href={`/gallery/${event.id}`}>Galería</a><a href="/">Menú</a></header>{items.length>1&&<div className="projectControls"><button onClick={()=>setActive((active-1+items.length)%items.length)}>‹</button><span>{active+1}/{items.length}</span><button onClick={()=>setActive((active+1)%items.length)}>›</button></div>}<aside><b>{event.name}</b><span>#Orbit360</span></aside></main>}
  return <main className="gallery shell"><header className="topbar"><div><a className="brand" href="/">◎ ORBIT 360</a><p>{event.client}</p></div><nav className="headerActions"><a href="/">Menú principal</a><a href={`/project/${event.id}`} target="_blank">Proyectar</a><a className="primary" href={`/booth/${event.id}`}>Abrir cabina</a></nav></header><section className="galleryHero" style={{background:`linear-gradient(120deg,${event.theme.primary},${event.theme.accent})`}}><span className="eyebrow">GALERÍA DEL EVENTO</span><h1>{event.name}</h1><p>{items.length} recuerdos listos para revivir y compartir.</p></section><div className="galleryToolbar"><div><button className={view==='preview'?'active':''} onClick={()=>setView('preview')}>▦ Vista previa</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>☷ Listado</button><button className={view==='detail'?'active':''} onClick={()=>setView('detail')}>▤ Detalle</button></div><span>Página {page} de {pages}</span></div>{items.length?<div className={`mediaGrid view-${view}`}>{shown.map(item=><article key={item.id} onClick={()=>setSelected(item)}>{item.kind==='video'?<video src={fileUrl(item)} muted playsInline/>:<img src={fileUrl(item)} alt={item.filename||'Foto del evento'}/>}<div className="mediaMeta"><div><b>{item.filename||`${item.kind}-${item.id.slice(0,8)}`}</b><small>{new Date(item.createdAt).toLocaleString('es-CL')} · {item.kind==='video'?'Video':'Foto'}</small></div><div className="rowActions"><button onClick={e=>{e.stopPropagation();setSelected(item)}}>Previsualizar</button><a onClick={e=>e.stopPropagation()} href={`${fileUrl(item)}?download=1`}>Descargar ↓</a></div></div></article>)}</div>:<div className="empty"><b>Aún no hay capturas</b><p>Abre la cabina y crea el primer recuerdo.</p></div>}{pages>1&&<nav className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>← Anterior</button>{Array.from({length:pages},(_,i)=><button key={i} className={page===i+1?'active':''} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Siguiente →</button></nav>}{selected&&<div className="previewModal" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="previewMedia">{selected.kind==='video'?<video src={fileUrl(selected)} controls autoPlay playsInline/>:<img src={fileUrl(selected)} alt="Vista ampliada"/>}</div><aside><span className="eyebrow">COMPARTIR CAPTURA</span><h2>{selected.filename||'Recuerdo Orbit 360'}</h2>{qr&&<img className="qr" src={qr} alt="Código QR de la captura"/>}<p>El QR abre directamente esta previsualización.</p><div className="stackActions"><a className="primary" href={`${fileUrl(selected)}?download=1`}>Descargar archivo</a><button onClick={()=>copy(selected)}>{copied?'Enlace copiado ✓':'Copiar enlace de descarga'}</button></div></aside></section></div>}</main>
}
